const ACHIEVEMENT_CRITERIA_TYPE = {
  XP: 'xp',
  STREAK: 'streak',
  COUNT: 'count',
};

const BADGE_DEFINITIONS = [
  {
    badgeId: 'xp_rookie_100',
    title: 'XP Rookie',
    description: 'Reach 100 total XP.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.XP,
    metricKey: 'total_xp',
    threshold: 100,
  },
  {
    badgeId: 'xp_builder_300',
    title: 'XP Builder',
    description: 'Reach 300 total XP.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.XP,
    metricKey: 'total_xp',
    threshold: 300,
  },
  {
    badgeId: 'xp_grinder_600',
    title: 'XP Grinder',
    description: 'Reach 600 total XP.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.XP,
    metricKey: 'total_xp',
    threshold: 600,
  },
  {
    badgeId: 'xp_elite_1000',
    title: 'XP Elite',
    description: 'Reach 1000 total XP.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.XP,
    metricKey: 'total_xp',
    threshold: 1000,
  },
  {
    badgeId: 'xp_legend_2000',
    title: 'XP Legend',
    description: 'Reach 2000 total XP.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.XP,
    metricKey: 'total_xp',
    threshold: 2000,
  },
  {
    badgeId: 'streak_ignite_3',
    title: 'Streak Ignite',
    description: 'Maintain a 3-day streak.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.STREAK,
    metricKey: 'current_streak',
    threshold: 3,
  },
  {
    badgeId: 'streak_runner_7',
    title: 'Streak Runner',
    description: 'Maintain a 7-day streak.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.STREAK,
    metricKey: 'current_streak',
    threshold: 7,
  },
  {
    badgeId: 'streak_climber_14',
    title: 'Streak Climber',
    description: 'Maintain a 14-day streak.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.STREAK,
    metricKey: 'current_streak',
    threshold: 14,
  },
  {
    badgeId: 'streak_anchor_21',
    title: 'Streak Anchor',
    description: 'Maintain a 21-day streak.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.STREAK,
    metricKey: 'current_streak',
    threshold: 21,
  },
  {
    badgeId: 'streak_titan_30',
    title: 'Streak Titan',
    description: 'Maintain a 30-day streak.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.STREAK,
    metricKey: 'current_streak',
    threshold: 30,
  },
  {
    badgeId: 'count_dsa_10',
    title: 'Problem Solver',
    description: 'Solve 10 DSA problems.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.COUNT,
    metricKey: 'dsa_solved_count',
    threshold: 10,
  },
  {
    badgeId: 'count_mock_5',
    title: 'Mock Challenger',
    description: 'Complete 5 mock interviews.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.COUNT,
    metricKey: 'mock_count',
    threshold: 5,
  },
  {
    badgeId: 'count_project_3',
    title: 'Shipper',
    description: 'Ship 3 projects.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.COUNT,
    metricKey: 'project_shipped_count',
    threshold: 3,
  },
  {
    badgeId: 'count_behavioral_10',
    title: 'Story Polisher',
    description: 'Complete 10 behavioral practice sessions.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.COUNT,
    metricKey: 'behavioral_practice_count',
    threshold: 10,
  },
  {
    badgeId: 'count_quest_20',
    title: 'Consistency Core',
    description: 'Complete 20 daily quests.',
    criteriaType: ACHIEVEMENT_CRITERIA_TYPE.COUNT,
    metricKey: 'quest_completed_count',
    threshold: 20,
  },
];

module.exports = {
  ACHIEVEMENT_CRITERIA_TYPE,
  BADGE_DEFINITIONS,
};
