const PROJECT_STATUS = {
  IDEA: 'idea',
  PLANNING: 'planning',
  IN_PROGRESS: 'in_progress',
  BLOCKED: 'blocked',
  SHIPPED: 'shipped',
  ARCHIVED: 'archived',
};

const PROJECT_STATUS_ORDER = [
  PROJECT_STATUS.IDEA,
  PROJECT_STATUS.PLANNING,
  PROJECT_STATUS.IN_PROGRESS,
  PROJECT_STATUS.BLOCKED,
  PROJECT_STATUS.SHIPPED,
  PROJECT_STATUS.ARCHIVED,
];

const PROJECT_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
};

const PROJECT_PRIORITY_ORDER = [
  PROJECT_PRIORITY.LOW,
  PROJECT_PRIORITY.MEDIUM,
  PROJECT_PRIORITY.HIGH,
  PROJECT_PRIORITY.CRITICAL,
];

module.exports = {
  PROJECT_PRIORITY,
  PROJECT_PRIORITY_ORDER,
  PROJECT_STATUS,
  PROJECT_STATUS_ORDER,
};
